name: Build On Release

on:
  release:
    types: [published]

jobs:
  build-and-upload-linux:
    name: Generate And Upload Linux Build Files
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.11f1-base-0.15.0
    env:
      DOTNET_ROOT: '/opt/unity/Editor/Data/NetCore/Sdk-2.2.107'

    steps:
      - name: Install dependencies
        run: |
          apt update && apt install sudo
          sudo apt-get install -y zip
          sudo apt-get install -y make

      - name: Activate unity
        # exit code is 1 for manual activation
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit | echo "Activation finished"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        id: cache-library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.3.11-linux

      - name: Generate Build
        run: |
          make linux UNITY_EXECUTABLE=unity-editor
          export LINUX_BUILD_NAME=$(ls Build/*Linux.zip | sed -e 's/Build\///')
          echo "LINUX_BUILD_NAME=$LINUX_BUILD_NAME" >> $GITHUB_ENV

      - name: Upload Linux Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token:  ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./Build/${{ env.LINUX_BUILD_NAME }}
          asset_name: ${{ env.LINUX_BUILD_NAME }}

  build-and-upload-windows:
    name: Generate And Upload Windows Build Files
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.11f1-windows-mono-0.15.0
    env:
      DOTNET_ROOT: '/opt/unity/Editor/Data/NetCore/Sdk-2.2.107'

    steps:
      - name: Install dependencies
        run: |
          apt update && apt install sudo
          sudo apt-get install -y zip
          sudo apt-get install -y make

      - name: Activate unity
        # exit code is 1 for manual activation
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit | echo "Activation finished"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        id: cache-library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.3.11-windows

      - name: Generate Build
        run: |
          make windows UNITY_EXECUTABLE=unity-editor
          export WINDOWS_BUILD_NAME=$(ls Build/*Windows.zip | sed -e 's/Build\///')
          echo "WINDOWS_BUILD_NAME=$WINDOWS_BUILD_NAME" >> $GITHUB_ENV

      - name: Upload Windows Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./Build/${{ env.WINDOWS_BUILD_NAME }}
          asset_name: ${{ env.WINDOWS_BUILD_NAME }}

  build-and-upload-webgl:
    name: Generate And Upload WebGL Build Files
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.11f1-webgl-0.15.0
    env:
      DOTNET_ROOT: '/opt/unity/Editor/Data/NetCore/Sdk-2.2.107'

    steps:
      - name: Install dependencies
        run: |
          apt update && apt install sudo
          sudo apt-get install -y zip
          sudo apt-get install -y make

      - name: Activate unity
        # exit code is 1 for manual activation
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit | echo "Activation finished"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        id: cache-library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.3.11-webgl

      - name: Generate Build
        run: |
          make webgl UNITY_EXECUTABLE=unity-editor
          export WEB_BUILD_NAME=$(ls Build/*Web.zip | sed -e 's/Build\///')
          echo "WEB_BUILD_NAME=$WEB_BUILD_NAME" >> $GITHUB_ENV

      - name: Upload Web Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./Build/${{ env.WEB_BUILD_NAME }}
          asset_name: ${{ env.WEB_BUILD_NAME }}
